# Performing all imports
##### These are all the imports required for the project

In [26]:
# Performing all imports
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Creating all the required datasets

In [ ]:
water_quality_training = pd.read_csv('C:\EY AI & Data Challenge\Datasets\water_quality_training_dataset.csv')
terraclimate_features_training = pd.read_csv(r'C:\EY AI & Data Challenge\Datasets\terraclimate_features_training.csv')
landsat_features_training = pd.read_csv('C:\EY AI & Data Challenge\Datasets\landsat_features_training.csv')

<>:2: SyntaxWarning: "\E" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\E"? A raw string is also an option.
<>:4: SyntaxWarning: "\E" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\E"? A raw string is also an option.
<>:2: SyntaxWarning: "\E" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\E"? A raw string is also an option.
<>:4: SyntaxWarning: "\E" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\E"? A raw string is also an option.
C:\Users\SW559CS\AppData\Local\Temp\ipykernel_37192\2357433369.py:2: SyntaxWarning: "\E" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\E"? A raw string is also an option.
  water_quality_training = pd.read_csv('C:\EY AI & Data Challenge\Datasets\water_quality_training_dataset.csv')
C:\Users\SW559CS\AppData\Local\Temp\ipykernel_37192\2357433369.py:4: SyntaxWarning: "\E" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\E"? A raw string is also an option.
  landsat_features_training = pd.read_csv('C:\EY AI & Data Challenge\Datasets\landsat_features_training.csv')

# Combining all datasets into one

In [28]:
# Combining all datasets
water_terras_df = water_quality_training.merge(
    terraclimate_features_training,
    on=["Latitude", "Longitude", "Sample Date"],
    how="left"
)

complete_merge = water_terras_df.merge(
    landsat_features_training,
    on=["Latitude", "Longitude", "Sample Date"],
    how="left"
)

display(complete_merge)

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,nir,green,swir16,swir22,NDMI,MNDWI
0,-28.760833,17.730278,02-01-2011,128.912,555.0,10.0,174.20000,11190.0,11426.0,7687.5,7645.0,0.185538,0.195595
1,-26.861111,28.884722,03-01-2011,74.720,162.9,163.0,124.10000,17658.5,9550.0,13746.5,10574.0,0.124566,-0.180134
2,-26.450000,28.085833,03-01-2011,89.254,573.0,80.0,127.50000,15210.0,10720.0,17974.0,14201.0,-0.083293,-0.252805
3,-27.671111,27.236944,03-01-2011,82.000,203.6,101.0,129.70000,14887.0,10943.0,13522.0,11403.0,0.048048,-0.105416
4,-27.356667,27.286389,03-01-2011,56.100,145.1,151.0,129.20000,16828.5,9502.5,12665.5,9643.0,0.141147,-0.142683
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9314,-27.527500,30.858056,23-12-2015,38.900,134.0,20.0,166.30000,15296.5,10043.0,16381.0,14443.0,-0.034236,-0.239858
9315,-26.861111,28.884722,23-12-2015,115.800,388.0,20.0,182.40001,15642.5,10294.5,17045.5,14710.0,-0.042921,-0.246928
9316,-26.984722,26.632278,23-12-2015,104.874,835.0,148.0,207.80000,14945.0,10732.0,18303.0,16281.0,-0.100999,-0.260754
9317,-27.935000,26.126667,23-12-2015,128.000,305.0,28.0,222.80000,14727.5,11051.0,18420.0,15724.5,-0.111396,-0.250042
9318,-29.744167,29.905833,31-12-2015,37.000,86.4,5.0,161.00000,15344.5,10461.5,14948.5,12747.0,0.013072,-0.176584

# Cleaning the dataset

In [29]:
# Checking for any missing values
complete_merge.isna().sum()

# Dropping all missing data
complete_merge.dropna(inplace=True)

display(complete_merge)

# Verifying that all data is of the correct datatype
complete_merge.dtypes

# Converting the "Sample Data" column to the correct datatype
complete_merge["Sample Date"] = pd.to_datetime(complete_merge["Sample Date"], format= r"%d-%m-%Y")

# Verifying that the datatypes are all correct now
complete_merge.dtypes

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,nir,green,swir16,swir22,NDMI,MNDWI
0,-28.760833,17.730278,02-01-2011,128.912,555.0,10.0,174.20000,11190.0,11426.0,7687.5,7645.0,0.185538,0.195595
1,-26.861111,28.884722,03-01-2011,74.720,162.9,163.0,124.10000,17658.5,9550.0,13746.5,10574.0,0.124566,-0.180134
2,-26.450000,28.085833,03-01-2011,89.254,573.0,80.0,127.50000,15210.0,10720.0,17974.0,14201.0,-0.083293,-0.252805
3,-27.671111,27.236944,03-01-2011,82.000,203.6,101.0,129.70000,14887.0,10943.0,13522.0,11403.0,0.048048,-0.105416
4,-27.356667,27.286389,03-01-2011,56.100,145.1,151.0,129.20000,16828.5,9502.5,12665.5,9643.0,0.141147,-0.142683
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9314,-27.527500,30.858056,23-12-2015,38.900,134.0,20.0,166.30000,15296.5,10043.0,16381.0,14443.0,-0.034236,-0.239858
9315,-26.861111,28.884722,23-12-2015,115.800,388.0,20.0,182.40001,15642.5,10294.5,17045.5,14710.0,-0.042921,-0.246928
9316,-26.984722,26.632278,23-12-2015,104.874,835.0,148.0,207.80000,14945.0,10732.0,18303.0,16281.0,-0.100999,-0.260754
9317,-27.935000,26.126667,23-12-2015,128.000,305.0,28.0,222.80000,14727.5,11051.0,18420.0,15724.5,-0.111396,-0.250042
9318,-29.744167,29.905833,31-12-2015,37.000,86.4,5.0,161.00000,15344.5,10461.5,14948.5,12747.0,0.013072,-0.176584

Latitude                                float64
Longitude                               float64
Sample Date                      datetime64[us]
Total Alkalinity                        float64
Electrical Conductance                  float64
Dissolved Reactive Phosphorus           float64
pet                                     float64
nir                                     float64
green                                   float64
swir16                                  float64
swir22                                  float64
NDMI                                    float64
MNDWI                                   float64
dtype: object

# Total Alkalinity Prediction

In [ ]:
# Splitting the training and target columns
X = complete_merge.drop(columns=['Total Alkalinity'])
y = complete_merge['Total Alkalinity']

# Creating the train test splits
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creating a Linear Regression Model